### ISSUE TITLE
A page not uploading due to a database error causes the cursor to be permanently busy in app

### ISSUE THREAD

**Issue by Wreckstation** [syntaxaire/qud-wiki#31]
Attempting to upload carbide dagger with QBE causes a DB error (possibly because there is another cargo storage on the page? Manually updated it myself). This is only a visual bug, since you are still able to do normal functions with the mouse.
The error:
`mwclient.errors.APIError: ('internal_api_error_DBTransactionStateError', '[7224e3ea0d47644c7f9849c9] Exception caught: A database query error has occurred. This may indicate a bug in the software.', None)`

**Comment by egocarib** [comment]
Seems like that would mean the code path is never getting to
https://github.com/syntaxaire/qud-wiki/blob/620255f2b0ec1117701fa9e7afc7cad9d86053df/qud_explorer.py#L313
when an error is encountered.

My guess is that the error encountered during the upload was not a `ValueError`, which is the only type of error we're currently catching in `upload_selected_tiles` . Because the error is unhandled, we never reach line 313 referenced above which would restore the cursor.

I'm not too familiar with try/catching errors in python but I think we need to have a generic catch-all that restores the cursor before exiting the `upload_selected_tiles` method.
